cmdTranslate = {'chicken': 'создал(а) курицу', 'cow': 'создал(а) корову', 'pig': 'создал(а) свинью',
                'wolf': 'призвал(а) волка', 'cookie': 'дал(а) печеньку', '6': 'вылечил(а) всех',
                'iron_sword': 'дал(а) железный меч', 'wooden_sword': 'дал(а) деревянный меч',
                'stone_axe': 'дал(а) каменный топор', 'iron_axe': 'дал(а) железный топор',
                'netherex:frosted_amedian_sword': 'дал(а) ледяной меч',
                'twilightforest:ironwood_sword': 'дал(а) древожелезный меч',
                'twilightforest:twilight_scepter': 'дал(а) волшебный скипетр',
                'thaumcraft:elemental_sword': 'дал(а) стихийный меч', 'millenaire:mayanmace': 'дал(а) булаву',
                'diamond_shovel': 'дал(а) алмазную лопату', 'millenaire:yumibow': 'дал(а) Юми лук',
                'bow': 'дал(а) простой лук', 'fishing_rod': 'дал(а) удочку',
                'twilightforest:triple_bow': 'дал(а) тройной лук', 'twilightforest:ice_bow': 'дал(а) ледяной лук',
                'twilightforest:lifedrain_scepter': 'дал(а) скипетр жизни',
                'millenaire:seljukbow': 'дал(а) длинный лук', 'thaumcraft:turret': 'дал(а) турель',
                'iron_boots': 'дал(а) железные ботинки', 'iron_chestplate': 'дал(а) железный нагрудник',
                'golden_helmet': 'дал(а) золотой шлем', 'golden_leggings': 'дал(а) золотые штаны',
                'diamond_chestplate': 'дал(а) алмазный нагрудник', 'diamond_helmet': 'дал(а) алмазный шлем',
                'diamond_boots': 'дал(а) алмазные ботинки', 'thaumcraft:thaumium_helmet': 'дал(а)  тхаум-шлем',
                'thaumcraft:thaumium_leggings': 'дал(а) тхаум-штаны',
                'twilightforest:yeti_helmet': 'дал(а) шлем "Йети"',
                'twilightforest:yeti_leggings': 'дал(а) штаны "Йети"',
                'galacticraftplanets:titanium_chestplate': 'дал(а) титановый нагрудник',
                'galacticraftplanets:titanium_boots': 'дал(а) титановые ботинки',
                'ic2:alloy_chestplate': 'дал(а) композитный нагрудник', '': '',
                'thaumcraft:crystal_aer': 'дал(а) кристал воздуха',
                'arrow': 'дал(а) стрелы', 'thaumcraft:crystal_ignis': 'дал(а) кристал огня', 'piston': 'дал(а) поршень',
                'leather': 'дал(а) кожу', 'redstone_block': 'дал(а) блок редстоуна',
                'coal_block': 'дал(а) блок угля', 'iron_ingot': 'дал(а) железный слиток',
                'iron_ore': 'дал(а) железную руду', 'gold_ingot': 'дал(а) золотой слиток',
                'ic2:dynamite_sticky': 'дал(а) динамит', 'bookshelf': 'дал(а) книжную полку', 'quartz': 'дал(а) кварц',
                'repair': 'восстановил(а) забор', 'zombie': 'призвал(а) зомби',
                'zombie_villager': 'призвал(а) зомби жителя', 'husk': 'призвал(а) кадавра',
                'galacticraftcore:evolved_zombie': 'призвал(а) инопланетного зомби',
                'zombie_pigman': 'призвал(а) свинозомби',
                'thaumcraft:brainyzombie': 'призвал(а) умный зомби',
                'thaumcraft:giantbrainyzombie': 'призвал(а) зомби гиганта',
                'thaumcraft:inhabitedzombie': 'призвал(а) зараженного зомби',
                'skeleton': 'призвал(а) скелета', 'stray': 'призвал(а) зимогора',
                'galacticraftcore:evolved_skeleton': 'призвал(а) инопланетного скелета',
                'wither_skeleton': 'призвал(а) скелета-иссушителя', 'creeper': 'призвал(а) крипера',
                'galacticraftcore:evolved_creeper': 'призвал(а) инопланетного крипера',
                'netherex:spore_creeper': 'призвал(а) спорового крипера', ',powered:1': ' заряженного',
                ',Glowing:1,Health:40,Attributes:[{Name:"generic.maxHealth",Base:40}],Fire:1277951,ExplosionRadius:50,ActiveEffects:[{Id:12,Amplifier:0,Duration:2147483647}]': 'радиоактивного',
                'ghast': 'призвал(а) Гаста', 'netherex:frost': 'призвал(а) фроста', 'blaze': 'призвал(а) ифрита',
                'witch': 'призвал(а) ведьму', 'netherex:spinout': 'призвал(а) вращателя',
                'netherex:brute': 'призвал(а) "Зверя"', 'twilightforest:fire_beetle': 'призвал(а) огненного жука',
                'twilightforest:goblin_knight_lower': 'призвал(а) гоблина рыцаря',
                'twilightforest:minotaur': 'призвал(а) минотавра',
                'twilightforest:pinch_beetle': 'призвал(а) жука-щипца', 'twilightforest:redcap': 'призвал(а) гоблина',
                'twilightforest:tower_golem': 'призвал(а) башенного голема',
                'twilightforest:troll': 'призвал(а) тролля', 'twilightforest:yeti': 'призвал(а) Йети',
                'thaumcraft:cultistknight': 'призвал(а) рыцаря культиста',
                'thaumcraft:eldritchguardian': 'призвал(а) древнего стража',
                'thaumcraft:cultistcleric': 'призвал(а) культиста клерика',
                'thaumcraft:taintacle': 'призвал(а) тинтаклю',
                'thaumcraft:taintseedprime': 'призвал(а) "Семя пустоты" большое',
                'thaumcraft:taintseed': 'призвал(а) "Семя пустоты"',
                'thaumcraft:eldritchcrab': 'призвал(а) древнего краба',
                'twilightforest:armored_giant': 'призвал(а) бронированного гиганта',
                'twilightforest:knight_phantom': 'призвал(а) фантома',
                'mowziesmobs:frostmaw': 'призвал(а) "Ледочрева"', 'twilightforest:lich': 'призвал(а) лича',
                'galacticraftplanets:creeper_boss': 'призвал(а) крипер босса',
                'galacticraftcore:evolved_skeleton_boss': 'призвал(а) скелета босса',
                'mowziesmobs:naga': 'призвал(а) летающую "Нагу"',
                'thaumcraft:cultistleader': 'призвал(а) лидера культистов',
                'twilightforest:naga': 'призвал(а) "Нагу"', 'mowziesmobs:barako': 'призвал(а) "Барако"',
                'thaumcraft:eldritchgolem': 'призвал(а) древнего голема',
                'thaumcraft:cultistportalgreater': 'призвал(а) огромный портал', 'lightning_bolt': 'призвал(а) молнию',
                'tnt': 'создал(а) динамит', 'escalade': 'провел(а) осадную лестницу',
                'wakeup': 'Оживил(а) всех мертвых!!'}
